# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "BBQ Theme"
license = "MIT"
licenselink = "https://github.com/matt-antone/bbq-hugo-site/blob/master/LICENSE"
description = ""
homepage = "http://bbqcss.com/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Matt Antone"
  homepage = "https://matthewantone.com"
